### ISSUE TITLE
Helper function to stop a node?

### ISSUE THREAD

**Issue by arjan** [bitwalker/ex_unit_clustered_case#6]
To stop a node during a testcase I currently use:

```
      Cluster.call(target_node, :init, :stop, [])
```

However this has 2 issues:

1. The cluster manager still tries to stop it on the exit of the test, which fails:

```
** (stop) exited in: ExUnit.ClusteredCase.Node.Manager.server_call(#PID<0.502.0>, :stop)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (ex_unit_clustered_case) lib/node/manager.ex:558: ExUnit.ClusteredCase.Node.Manager.server_call/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (ex_unit_clustered_case) lib/cluster.ex:338: ExUnit.ClusteredCase.Cluster.handle_call/3
```

2. Other tests inside the same `scenario` will (obviously) fail because one of the other tests stopped a node which the cluster manager did not expect.

So I think there could be a point for adding a `Cluster.stop_node(c, node_name)` call which stops a node inside a test (using `:init.stop()` or similar) and waits until it `:pang`s, and then maybe at the end of the testcase starts it again. WDYT?

**Comment by bitwalker** [comment]
@arjan I've added this in a branch called `feature/manual-stop`, could you take a look and test it out with your use case? There are two new functions `Cluster.stop_node(cluster, node)` and `Cluster.kill_node(cluster, node)`. Nodes are killed until the next time the test setup function runs (when the cluster gets started again, if the cluster is already up, then we call an internal function `Cluster.reset(cluster)` which restarts any stopped/killed nodes).

**Comment by arjan** [comment]
Great API, I tested it, and it... didn't work ;-) Mainly you forgot to set the pids to `nil` in the pidmap of the cluster. My PR #8 addresses this.
